@startuml Vote Rebroadcast

class VoteRebroadcaster {
	start()
	stop()
}

class VoteRebroadcastQueue {
	try_enqueue(vote, results)
	enqueue(vote)
	dequeue()
}

class RebroadcastProcessor {
	process_vote(vote)
}

class RebroadcastHistory


class AecEventProcessor

interface RepTiersConsumer {
	update_rep_tiers(tiers)
}

interface WalletRepsConsumer {
	udpate_wallet_reps(reps)
}

VoteRebroadcastQueue ..|> RepTiersConsumer
VoteRebroadcastQueue ..|> WalletRepsConsumer
VoteRebroadcaster --> VoteRebroadcastQueue
VoteRebroadcaster --> RebroadcastProcessor
RebroadcastProcessor --> MessageFlooder
RebroadcastProcessor --> RebroadcastHistory
AecEventProcessor --> VoteRebroadcastQueue: try_enqueue()

@enduml
