@startuml
package "rebroadcast" {
	class VoteRebroadcaster {
	  start()
	  stop()
	}

	class VoteRebroadcastQueue {
	  try_enqueue(vote, results)
	  enqueue(vote)
	  dequeue()
	}

	class RebroadcastProcessor {
	  process_vote(vote)
	}

	class WalletRepsCache{
	  have_half_rep()
	  exists(rep_key)
	}
}

class WalletRepresentatives
class AecEventProcessor

VoteRebroadcaster --> VoteRebroadcastQueue
VoteRebroadcaster --> RebroadcastProcessor
RebroadcastProcessor --> MessageFlooder
RebroadcastProcessor --> WalletRepsCache
WalletRepsCache --> WalletRepresentatives
AecEventProcessor --> VoteRebroadcastQueue: try_enqueue()
@enduml
